### ISSUE TITLE
Data not saved while rebooting docker

### ISSUE THREAD

**Issue by mvank** [rvleij/p1monitor#2]
Hi Robin, thank you for making a docker available for P1-Monitor.

While testing, I noticed that when I reboot my docker container, because of maintenance, i loose all information.
To make sure the data is still available after rebooting or recreating the container i needed to change the following:

--tmpfs /tmp --tmpfs /run --tmpfs /p1mon/mnt/ramdisk \   >>  -v /local path/p1mon/ramdisk:/p1mon/mnt/ramdisk:rw

**Comment by rvleij** [comment]
I've changed it in the readme, it's indeed a simple fix to create some persistency. I don't see any issue setting the ramdisk volume to a persistent mount (or even volume), I'll test it myself. Restarting docker is a bit like pulling the plug on the Pi in the "real" situation. But of course you don't do that and the built in controls for start/stop/restart. With Docker it's much easier to do that outside the control of p1mon. Thanks!
