### ISSUE TITLE
Connect P1 over LAN

### ISSUE THREAD

**Issue by hemant5400z** [rvleij/p1monitor#5]
Hi,

I just installed p1monitor using your docker image. Thanks for that.

My case is slighlty differnt as i do not run on a PI. I used your docker image to run in on my Synology NAS over the LAN.
So I used ser2net combining socat. some trial on error but works fine now and data is coming in the dashboard.

So instead of having a physical serial connection i now use it over the LAN, why -> because I use my P1 connection with several other applications like Domotcz. With this setup I can now have 10 smulate connections. This way I can avoid a Raspberry Pi and run P1/DOmoticz/DSMR wherever I want.

Thanks and keep up the good work.

**Comment by rvleij** [comment]
Great! Thanks for documenting. Maybe I should make a wiki with these tips or we just leave it as a closed issue for reference.

**Comment by mvank** [comment]
Hi @hemant5400z , can you share how you did setup ser2net with p1 monitor?
I am using now 2 physical connection, 1 for p1mon and 1 for home assistant.

**Comment by hemant5400z** [comment]
> Hi @hemant5400z , can you share how you did setup ser2net with p1 monitor? I am using now 2 physical connection, 1 for p1mon and 1 for home assistant.

Hi mvank,

1.First you need to install ser2net (not sure where your P1 is connected to physically).
2. convert the serial to an ip based connecting (i used udev to make sure i always have the correct device)
    you will need to set the serial device in the ser2net.conf for ser2net v3 it the line looks like this:
    ipv4,tcp,5000:raw:0:/dev/YOUR-P1-USB:115200 NONE 1STOPBIT 8DATABITS max-connections=10.
3. one that is doen you can telnet to the device remotely "telnet ip 5000" if all ok you will see the p1 messages.
4. on the p1monitor machine you will need to install socat
5. connect the p1monitor machine by doing this from the command line:
   socat pty,link=/dev/ttyUSB0,rawer,mode=777 tcp:P1-IPADDRESS:5000,retry=forever,interval=30
6. If all ok change the port in p1monitor to see if it connects properly and picks up the messages.
7. If this works create a script with the socat command with excute permissions call the script in the rc.local is you have a physical machine, if you run a docker you need to call the script in the start_all.sh.

Cheers,
Aniel

**Comment by hemant5400z** [comment]
@mvank 

Did you try above instructions?

Hemant
