### ISSUE TITLE
update to v1.4.1

### ISSUE THREAD

**Issue by WouterLS** [rvleij/p1monitor#6]
Hi,

any chance of updating to version 1.4.1 sometime?
https://www.ztatz.nl/p1-monitor-download-20211002-v1-4-1/

**Comment by rvleij** [comment]
I'm downloading that version now, I'll publish it tonight. Will take a bit to cross compile and push to Docker Hub.
It's been on my to-do list, but just so much other stuff to do. :)

**Comment by rvleij** [comment]
It's up now, I'll just update the git repo now as well and then we're current again. I'll try to keep an eye out for newer versions. Maybe build a build host in AWS that can read the image without me having to install it to an actual Pi4 and copying over the files...
