### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by EddyGitH** [rvleij/p1monitor#8]
Hi, i wanted to give p1monitor a testrun to see how it works and installed it as described. the web version is starting but not showing any data. So i looked in the log, there i found this issue. (please be aware i am a noob on raspberry PI).

I updated the pyyaml but no luck. 
What to do next? Please assist.
regards
Edwin

**Comment by rvleij** [comment]
Hi, are you sure you are running the docker version and not some other install? Because all modules required are already part of the Docker image, so it's kind of weird you get a modulenotfound error? Can you paste the logs (and how you get the logs)?

**Comment by EddyGitH** [comment]
Hi, thanks for the quick response. Yes i am using the docker, indeed it is very strange... but now i am looking better is see i ended up at another docker p1monitor instance.. as i can tell i installed the claassen version haha.
But i will reinstall the whole item again, see if that is helping. And if not I will try your version ;-)  
Sorry about the hassle!
