### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by WouterLS** [rvleij/p1monitor#9]
Any chance on an update to the latest version?

**Comment by rvleij** [comment]
I will try today. I was super late with the previous version, which I fixed just a few weeks ago. Thought I was safe for a while now. :-))

**Comment by rvleij** [comment]
Or do you mean the source code? Because that I didn’t update after the latest changes. Can fix that if you’d like of course.

**Comment by WouterLS** [comment]
I think 1.7.0 is out for some time now.
https://www.ztatz.nl/p1-monitor-download-20220601-v1-7-0/

**Comment by rvleij** [comment]
I'll close this issue, because I released 1.7 a while ago, currently I'm working on 2.0 (it's in testing), but I'm having some issues with the python modules in the new bullseye.
